### PR TITLE
legislators.json updated to 114th; real addresses for sens

### PR DESCRIPTION
**Pull request by rshorey**
legislators from the 113rd congress removed, 114th added to legislators.json. I also put in true addresses for Senators - not needed for contact-congress stuff, but helpful if anyone wants to geocode or use google civic.

### CODE REVIEW

**Comment by rshorey** [comment]
Just wanted to make sure someone who can edit/merge in this repo is keeping an eye on it. Would that be you, @sinak? We need legislators.json updated before we can start collecting new contact-congress yamls. Thanks!

**Comment by j-ro** [comment]
@rshorey, you want me to merge?

**Comment by rshorey** [comment]
yes please!

**Comment by sinak** [comment]
Sorry Rachel! If you need to get me, usually an email is a better option than a Github mention. Though I'm also going to whitelist Github comments from you to show up in my inbox :).

**Pull request merged**
